name = "playground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["playground"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Playground"
srcDir = "lib"

[[lean_exe]]
name = "playground"
root = "Main"
